<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Substance\Substance.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\**">
      <LogicalName>$(AssemblyName)/Assets/%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  

</Project>
